### ISSUE TITLE
new attached keyboard not covered by kloak

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#17]
Perhaps systemd is not the right tool to start kloak. When attaching a new keyboard, it will no be automatically covered by kloak. Perhaps udev would be better.

**Comment by vmonaco** [comment]
I agree. This would also make device discovery easier. DEVNAME could be passed as an argument to kloak.

It might also make sense to have a separate kloak process for each device (keyboard or mouse) since the obfuscation params could be different.

Could kloak be started by a udev rule, then treated as a service? Using SYSTEMD_WANTS instead of RUN? This would still enable control with systemctl.
https://unix.stackexchange.com/questions/436666/run-service-after-ttyusb0-becomes-available
https://www.freedesktop.org/software/systemd/man/systemd.device.html

**Comment by RyanOblivion112** [comment]
I'm not sure if this should be added as a new issue but it seems relevant here.

KLOAK currently doesn't support being used with something like a USB switch. Currently if you specify a USB device under /dev/input/ to be used, then use the USB switch to work on another computer and switch back KLOAK will silently fail to function. This is presumably due to the device assigned to KLOAK momentarily disappearing from /dev/input/, even though it reappears with the same name KLOAK does not resume processing it's input despite continuing to run without any errors.

**Comment by adrelanos** [comment]
Was done in https://github.com/Whonix/kloak/pull/1
