### ISSUE TITLE
Clarification on intended behavior of random()

### ISSUE THREAD

**Issue by qua3k** [vmonaco/kloak#37]
Hello, I noticed that you use the `random()` function but it does not appear to be explicitly seeded and will use a seed of `1`. 

I am asking for clarification on whether this is intended behavior. Additionally, I hope you are aware that `random()` is not suitable for generating secure random numbers.

**Comment by vmonaco** [comment]
Thanks for pointing this out. That's not the intended behavior, and delays should be randomly generated in a secure way.

I don't think recovering the seed from observing the event times alone would be practical because there's some level of noise even without using kloak (I could be wrong about this), *but* the seed could absolutely be recovered through a cross layer attack:
https://arxiv.org/abs/2012.07432

At the very least, we need a call to srand() in there. But it would be better to use a secure PRNG. Any suggestions? OpenSSL?

**Comment by qua3k** [comment]
> it would be better to use a secure PRNG. Any suggestions? OpenSSL?

OpenSSL's RNG has had numerous dangerous vulnerabilities in the past and I don't recommend you use it. Opt for [libsodium's](https://github.com/jedisct1/libsodium) `randombytes`.

**Comment by vmonaco** [comment]
fixed by #38
