### ISSUE TITLE
mouse click obfuscation

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#51]
When enabling debug mode `-v` I can see that mouse movements result in journal output. Not so for mouse clicks.

Are mouse clicks already obfuscated? Is this implemented or requires further work?

**Comment by skyzzuu** [comment]
Yeah they have delay added to them. In the output, they'll be event type 1 (EV_KEY) and have a code of 272 (BTN_LEFT) for the left mouse button or 273 (BTN_RIGHT) for the right mouse buttn. I can see them in my output, they usually just get flooded by EV_REL events around them since the mouse will typically move at least a little bit when clicking one of the buttons. Then either 1 or 0 for value are button down and button released, but I can't remember which is which. 



Towards the top of the large for loop in main_loop(), there are the following lines which will add delay to any events that aren't EV_SYN:

// syn events are not delayed
if (ev.type == EV_SYN) {
        random_delay = lower_bound;
} else {

**Comment by ArrayBolt3** [comment]
Mouse clicks seem to be obfuscated for me when running kloak directly (via `make && sudo ./kloak -d250 -v`). There's definitely a noticeable delay between when I click and when the click registers, and that delay has some randomization in it. I can also see the verbose output from kloak immediately responding to both when I click the mouse button and when I release it.

**Comment by ArrayBolt3** [comment]
Did some more testing using Whonix and the kloak systemd service (this time using a delay of `-d 1000` to make it easier to see if there was randomization occurring or not). There was what appeared to be noticeable randomization occurring in mouse click delays. Also tried disabling the systemd service in Whonix and just running kloak directly in verbose mode - there were definite events being generated for both click and release events.

**Comment by adrelanos** [comment]
Great!
