### ISSUE TITLE
Kloak refusing to start up on boot, will not accept some CLI commands, and mouse fingerprinting is not being enabled.

### ISSUE THREAD

**Issue by kloakthrowaway1993** [vmonaco/kloak#56]
_(Even though this is on a Whonix test VM, I am reporting this as a bug because it seems to be a prima facie case of a program being anal about exceptions rather than a problem with Whonix itself. I have already confirmed that this is the latest version of Kloak based on the new code on my KVM machine.) _

I was trying to run kloak with `sudo kloak -d 1000 -v` and it outputted:

`Found keyboard at: /dev/input/event0
Found mouse at: /dev/input/event2
Found keyboard at: /dev/input/event3
Found mouse at: /dev/input/event4
Found mouse at: /dev/input/event5
Waiting 500 ms...
Could not grab: /dev/input/event0
zsh: exit 1     sudo kloak -d 1000 -v`

Huh, weird. 

I try `sudo systemctl restart kloak` and all I get is nothing. No error message.

I then try a hyper-specific command that makes it read at event3 and dodging the whole scanning of event0 which seems to be the main culprit: 

`sudo kloak -d 500 -r /dev/input/event3 -v`

To my surprise, this actually worked. What doesn't work is the mouse fingerprinting cloaking. No evidence that this is being used is at all present within the verbose logs.

If either a solution or better ways to troubleshoot this are presented, I will be ecstatic. A way to point kloak to the keyword and mouse is preferable, but a full fix is a bonus.

**Comment by skyzzuu** [comment]
Regarding the mouse movement obfuscation, I cancelled my PR that had it because the code that added qubes support wasn't needed anymore because of a PR with qubes that adds support into the gui-agent, so that has not been added yet. I am working on breaking up that original PR into several smaller PRs and one of those will have the mouse movement obfuscation in it.


Regarding the other issues, would you mind following the instructions here and pasting a copy of kloak's logs please?

https://www.whonix.org/wiki/Keystroke_Deanonymization#Kloak_Debug_Mode


Also, are you using the Whonix stable repo, Testers repo, Developers repo, or are you pulling directory from this repository?

**Comment by skyzzuu** [comment]
Also, do you currently have the kloak service running when you are trying to run kloak manually?

If you run: `sudo systemctl status kloak.service` and it says it's running, you can't manually run kloak by running `sudo kloak` at the same time.

The manually run kloak is going to detect virtual devices created by the kloak service as either keyboards or mice and try to grab them, which will cause it to run into issues.

If you really want to manually run kloak instead of using the service, you're going to need to disable and stop it `sudo systemctl disable --now kloak.service` then do a reboot to make sure all the devices are cleaned up. Then you should be able to run kloak manually using `sudo kloak`.

**Comment by kloakthrowaway1993** [comment]
> Regarding the mouse movement obfuscation, I cancelled my PR that had it because the code that added qubes support wasn't needed anymore because of a PR with qubes that adds support into the gui-agent, so that has not been added yet. I am working on breaking up that original PR into several smaller PRs and one of those will have the mouse movement obfuscation in it.
> 
> Regarding the other issues, would you mind following the instructions here and pasting a copy of kloak's logs please?
> 
> https://www.whonix.org/wiki/Keystroke_Deanonymization#Kloak_Debug_Mode
> 
> Also, are you using the Whonix stable repo, Testers repo, Developers repo, or are you pulling directory from this repository?

Hi, and sorry for the late reply.

The mouse obfuscation works and your solution of disabling the service then manually running it worked. It appears that the Whonix project took the mouse obfuscation straight from the git.

Thank you for the things you do.

**Comment by adrelanos** [comment]
Or better a `/lib/systemd/system/kloak.service.d/30_user.conf` drop-in file because `/lib/systemd/system/kloak.service` gets overwritten when the kloak gets updated.

```
[Service]
ExecStart=/usr/sbin/kloak -v
```

This is a systemd feature.
