### ISSUE TITLE
replace strncpy with safer function for better security

### ISSUE THREAD

**Issue by adrelanos** [vmonaco/kloak#66]
After https://github.com/vmonaco/kloak/pull/65 was either merged or rejected... (Otherwise seems suggesting code changes on top of yet to be reviwed code changes.)

chatgpt suggested to replace `strncpy` with `strlcpy`.

```
#include <bsd/string.h> // Include this header for strlcpy
```

If that makes sense, I am happy to work on a PR soon after https://github.com/vmonaco/kloak/pull/65 has been decided.

----

In case you're wondering why I am doing these maybe nitpick (?), perfectionist (?) changes... I hope that with 100% memory allocation and string parsing correctness, a few rare corner cases bugs might be fixed:

* https://github.com/vmonaco/kloak/issues/12
* https://github.com/vmonaco/kloak/issues/31

Might also fix:

* https://github.com/vmonaco/kloak/issues/35

**Comment by skyzzuu** [comment]
Another option that might provide even better protection is to change main to use c++ instead of c. I ran a quick test, and it it only requires changing 2 lines in the makefile and 3 lines in main. Once it's changed to c++, kloak can use c++'s string objects in place of c strings which automatically track their length and automatically check the length of the source and destination string

**Comment by ArrayBolt3** [comment]
See https://github.com/vmonaco/kloak/issues/35#issuecomment-2368986182, tl;dr: I think using `strtcpy` is probably a better option than `strlcpy`.

**Comment by adrelanos** [comment]
Done in https://github.com/Whonix/kloak/pull/1
